# conf/strategy/momentum.yaml
# Momentum trading strategy configuration

defaults:
  - /model@_here_: default

# Model adjustments for momentum strategy
d_model: 96
d_fused: 384
dropout: 0.15

# Environment configuration
env:
  reward_type: "momentum"
  reward_scaling: 2.0
  trade_penalty: 0.05
  hold_penalty: 0.01

# Feature adjustments
feature:
  use_momentum: true
  use_tape_features: true
  use_volume_profile: true
  indicators:
    ema:
      - 9
      - 20
    macd:
      fast: 9
      slow: 21
      signal: 7
    rsi:
      period: 10

# Trading parameters
simulation:
  portfolio_config:
    initial_cash: 100000.0
  market_config:
    slippage_factor: 0.0015  # Higher slippage for momentum stocks
  execution_config:
    commission_per_share: 0.0

# Strategy-specific parameters
momentum:
  entry_threshold: 0.5  # Momentum strength required for entry
  exit_threshold: -0.2  # Momentum weakness for exit
  scale_in_levels: [0.25, 0.5, 0.75, 1.0]  # Position scaling
  take_profit_targets: [0.5, 1.0, 2.0]  # Percentage targets for profits
  stop_loss: 0.5  # Percentage for stop loss
  volume_surge_threshold: 3.0  # Relative volume threshold
  breakout_zones: ["whole_dollar", "half_dollar", "previous_high"]