# Trading strategy parameters for momentum trading
defaults:
  - /model@_here_: default.yaml

# Model adjustments for momentum strategy
d_model: 96
d_fused: 384
dropout: 0.15

# Entry conditions
entry:
  criteria:
    - whole_dollar_breakout
    - half_dollar_breakout
    - micro_pullback
  thresholds:
    momentum_strength: 0.5
    volume_surge: 5.0
    tape_speed: 3.0
    tape_imbalance: 0.7

# Exit conditions
exit:
  criteria:
    - take_profit
    - momentum_pause
    - decreased_volume
    - big_seller
  thresholds:
    profit_target: 0.02
    max_loss: 0.01
    volume_decrease: 0.5

# Position scaling parameters
scaling:
  in:
    levels: [0.25, 0.5, 0.75, 1.0]
  out:
    levels: [0.25, 0.5, 1.0]

# Technical indicators
indicators:
  ema: [9, 20, 200]
  vwap: true
  macd:
    fast: 12
    slow: 26
    signal: 9

# Support/resistance levels
support_resistance:
  use_whole_dollars: true
  use_half_dollars: true
  use_previous_highs_lows: true
  use_vwap: true

# Tape analysis parameters
tape_analysis:
  speed_threshold: 3.0
  imbalance_threshold: 0.7
  big_print_threshold: 5000

# Level 2 analysis parameters
l2_analysis:
  spread_tightening: true
  big_buyer_threshold: 10000
  big_seller_threshold: 10000