# config/model/transformer.yaml
# Transformer model configuration - synchronized with ModelConfig
# Feature Config
hf_seq_len: 60
hf_feat_dim: 20
mf_seq_len: 30
mf_feat_dim: 20
lf_seq_len: 30
lf_feat_dim: 20
portfolio_seq_len: 5
portfolio_feat_dim: 5
static_feat_dim: 5

# Model dimensions
d_model: 64
d_fused: 256

# Transformer parameters
hf_layers: 2
mf_layers: 2
lf_layers: 2
portfolio_layers: 2
hf_heads: 4
mf_heads: 4
lf_heads: 4
portfolio_heads: 4

# Output parameters
action_dim: [5, 4]
continuous_action: false

# Other parameters
dropout: 0.1