[tool.poetry]
name = "fx-ai"
version = "0.1.0"
description = ""
authors = ["XVll <onur@onurx.com>"]
readme = "README.md"
package-mode = false

[tool.poe.tasks]
# Training Tasks
init = "poetry run python scripts/run.py train --symbol MLGO"
train = "poetry run python scripts/run.py train --continue-training --symbol MLGO"
quick = "poetry run python scripts/run.py train --quick-test --symbol MLGO"

# Training with custom dates
train-date = "poetry run python scripts/run.py train --continue-training --symbol MLGO --start-date 2025-01-01 --end-date 2025-01-31"
train-days = "poetry run python scripts/run.py train --continue-training --symbol MLGO --days 5"

# Backtesting Tasks  
backtest = "poetry run python scripts/run.py backtest --symbol MLGO --start-date 2025-01-15 --end-date 2025-01-15"
backtest-week = "poetry run python scripts/run.py backtest --symbol MLGO --start-date 2025-01-13 --end-date 2025-01-17"
backtest-month = "poetry run python scripts/run.py backtest --symbol MLGO --start-date 2025-01-01 --end-date 2025-01-31"

# Hyperparameter Optimization
sweep = "poetry run python scripts/sweep.py --count 20"
sweep-quick = "poetry run python scripts/sweep.py --count 5"
sweep-long = "poetry run python scripts/sweep.py --count 50"

# Testing
test = "poetry run python -m pytest tests/ -xvs"
test-fast = "poetry run python -m pytest tests/ -x --tb=short"

# Utility Tasks
clean = "rm -rf outputs/* wandb/* __pycache__"
setup = "wandb login"
dashboard = "echo 'Dashboard will auto-launch during training at http://localhost:8050'"

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
numpy = "^2.2.5"
pandas = "^2.2.3"
wandb = "^0.19.11"
gymnasium = "^1.1.1"
matplotlib = "^3.10.3"
databento = "^0.54.0"
poetry-core = ">=1.0.0"
ta = "^0.11.0"
torch = "^2.7.0"
rich = "^14.0.0"
pydantic = "^2.11.5"
setuptools = "==80.8.0"
dash = "^3.0.4"
plotly = "^6.1.1"

[tool.poetry.group.dev.dependencies]
poethepoet = "^0.24.0"
pytest = "^7.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"