# config/wandb/default.yaml
# W&B configuration - synchronized with WandbConfig

# General settings
enabled: true
project_name: "fx-ai"
entity: null  # Your username or team name (null = default user)
log_code: true
log_model: true

# Logging frequency
log_frequency:
  steps: 1
  gradients: 100
  model_checkpoints: 5
  custom_charts: 5

# Advanced settings
watch_model: true
log_batch_metrics: false

# Custom visualizations
visualizations:
  position_charts: true
  trade_analysis: true
  market_indicators: true
  action_distributions: true