# Example curriculum configuration with symbol/date selection
# This shows how to configure curriculum stages with specific symbols and date ranges

curriculum:
  stage_1_beginner:
    enabled: true
    symbols: ["AAPL", "TSLA"]  # Train on these symbols only
    date_range: ["2025-05-01", "2025-05-31"]  # May 2025 only
    day_score_range: [0.7, 1.0]  # High quality days only
    roc_range: [0.05, 1.0]
    activity_range: [0.0, 1.0]
    max_updates: 500  # Switch after 500 updates
    max_episodes: null  # No episode limit
    max_cycles: null  # No cycle limit
  
  stage_2_intermediate:
    enabled: true
    symbols: ["AAPL", "TSLA", "NVDA"]  # Add more symbols
    date_range: ["2025-04-01", "2025-05-31"]  # Wider date range
    day_score_range: [0.5, 0.9]  # Medium quality days
    roc_range: [0.6, 1.0]
    activity_range: [0.3, 1.0]
    max_updates: 800
    max_episodes: null
    max_cycles: 10  # Or switch after 10 cycles through reset points
  
  stage_3_advanced:
    enabled: true
    symbols: []  # Empty = all available symbols
    date_range: [null, null]  # null = all available dates
    day_score_range: [0.3, 0.7]  # Lower quality, more challenging
    roc_range: [0.4, 1.0]
    activity_range: [0.2, 1.0]
    max_updates: null  # No limit - train indefinitely
    max_episodes: 5000  # Or switch after 5000 episodes
    max_cycles: null
  
  stage_4_specialization:
    enabled: false  # Disabled - only stages 1-3 will run
    symbols: []
    date_range: [null, null]
    day_score_range: [0.0, 1.0]
    roc_range: [0.0, 1.0]
    activity_range: [0.0, 1.0]
    max_updates: null
    max_episodes: null
    max_cycles: null

# Note: Symbols are only defined in curriculum stages
# The system will automatically discover all symbols from enabled stages