# Momentum-Based Training Configuration
# Enables proper day selection and curriculum learning

experiment_name: "momentum_training"

# Environment configuration
env:
  symbol: "MLGO"
  initial_capital: 25000.0
  max_episode_steps: 1000
  random_reset: true

# Model configuration  
model:
  d_model: 64
  n_heads: 8
  n_layers: 4
  dropout: 0.1

# Training configuration
training:
  learning_rate: 3e-4
  total_updates: 2000
  continue_training: true
  checkpoint_interval: 50
  early_stop_patience: 300

# Simulation configuration
simulation:
  allow_shorting: false
  random_start_prob: 0.9
  execution_delay_ms: 100
  commission_per_share: 0.005

# Data configuration
data:
  symbols: ["MLGO"]
  start_date: "2025-02-03"
  end_date: "2025-04-29"
  min_activity_score: 0.0
  max_activity_score: 1.0
  training_order: "activity_desc"
  auto_build_index: true

# Day Selection and Episode Management
day_selection:
  episodes_per_day: 10  # How many times to cycle through all reset points before switching day
  reset_point_quality_range: [0.3, 0.9]  # Quality score range for reset points to use
  day_switching_strategy: "exhaustive"  # "exhaustive" (use all reset points) or "random"

# Activity scoring
activity_scoring:
  reset_points_per_day: 25
  min_activity_threshold: 0.1
  front_side_threshold: 0.05
  back_side_threshold: -0.05

# Curriculum learning configuration
curriculum:
  stage_1_beginner:
    episode_range: [0, 1000]
    min_activity_score: 0.7
    direction_filter: "both"
  stage_2_intermediate:
    episode_range: [1000, 3000]
    min_activity_score: 0.5
    direction_filter: "both"
  stage_3_advanced:
    episode_range: [3000, 5000]
    min_activity_score: 0.2
    direction_filter: "both"
  stage_4_specialization:
    episode_range: [5000, null]
    min_activity_score: 0.0
    direction_filter: "both"

# Dashboard
dashboard:
  enabled: true
  port: 8051

# W&B tracking
wandb:
  enabled: true
  project: "fx-ai-momentum"
  tags: ["momentum", "curriculum", "day-switching"]