training:
  eval_frequency: 5  # Evaluate every 5 updates instead of default 25
  eval_episodes: 5   # Run 5 evaluation episodes

# Enable SHAP attribution analysis
model:
  enable_attribution: true
  shap_config:
    enabled: true
    update_frequency: 10  # Run SHAP every 10 updates
    max_samples_per_analysis: 5
    background_samples: 10
    methods:
      - gradient_shap
    primary_method: gradient_shap
    top_k_features: 50
    dead_feature_threshold: 0.001
    analyze_interactions: true
    save_plots: false  # Disable to reduce overhead during training
    log_to_wandb: true
    dashboard_update: true
    use_gpu: true

env:
  curriculum:
    stage_1:
      enabled: true
      symbols: ["MLGO"]
      date_range: ["2025-02-21", "2025-02-21"]
      day_score_range: [0.7, 1.0]
      roc_range: [0.0, 1.0]
      activity_range: [0.0, 1.0]
      max_updates: null    # Ensure at least 25 updates = 5 evaluations
      max_episodes: null
      max_cycles: 1   # Remove cycle limit to let max_updates control duration
    
    stage_2:
      enabled: false  # Disable other stages for now
      symbols: []
      date_range: [null, null]
      day_score_range: [0.5, 0.9]
      roc_range: [0.6, 1.0]
      activity_range: [0.3, 1.0]
      max_updates: 800
      max_episodes: null
      max_cycles: 10