# Normal training configuration - standard training with moderate settings
experiment_name: "normal_train"

# Standard model configuration
model:
  d_model: 128
  n_layers: 4
  n_heads: 8

# Standard training settings
training:
  rollout_steps: 512
  total_updates: 1000
  checkpoint_interval: 25
  batch_size: 64
  eval_frequency: 10
  eval_episodes: 5
  early_stop_patience: 150

# Standard episode length
env:
  max_episode_steps: 512
  max_steps: 512

# Full dataset
data:
  start_date: "2025-02-03"
  end_date: "2025-04-29"
  min_activity_score: 0.2

# Dashboard enabled
dashboard:
  enabled: true

# Wandb enabled
wandb:
  enabled: true
  tags: ["normal_train", "standard"]