# Normal training configuration with sniper 3-component scoring
experiment_name: "sniper_normal_train"

# Standard model configuration
model:
  d_model: 128
  n_layers: 4
  n_heads: 8

# Progressive training settings for sniper approach
training:
  rollout_steps: 2048    # Reduced from 8192 for faster updates (~34 min vs 136 min)
  total_updates: 1000
  checkpoint_interval: 25
  batch_size: 128        # Sniper batch size
  eval_frequency: 10
  eval_episodes: 5
  early_stop_patience: 150

# Progressive episode length (starts at Stage 1)
env:
  max_episode_steps: 256  # Stage 1: 4.3 minutes
  max_steps: 256

# Full dataset with 3-component filtering
data:
  start_date: "2025-02-03"
  end_date: "2025-04-29"
  min_activity_score: 0.0  # Use 3-component scoring instead

# Sniper momentum scanning configuration
momentum_scanning:
  min_daily_move: 0.10
  min_volume_multiplier: 2.0
  max_daily_move: null     # No caps - capture all volatility
  max_volume_multiplier: null
  direction_filter: "both"

# 3-Component scoring for sniper approach
three_component_scoring:
  direction_lookback_minutes: 10
  direction_volatility_threshold: 0.02
  roc_lookback_minutes: 5
  roc_volatility_window: 15
  activity_lookback_minutes: 15
  session_volume_window: 60
  reset_points_per_day: 120
  near_zero_threshold: 0.1
  direction_weight: 0.3
  roc_weight: 0.4
  activity_weight: 0.3

# Session-aware volume calculations
session_volume:
  use_session_specific_baselines: true
  volume_window_days: 10

# Progressive episode configuration
progressive_episodes:
  stage_1_length: 256
  stage_1_batch_size: 2048  # Reduced from 8192 for faster updates
  stage_1_offset_ratio: 1.0

# Sniper curriculum (starts with high-quality conditions)
curriculum:
  stage_1_beginner:
    episode_range: [0, 2000]
    episode_length: 256
    batch_size: 2048  # Reduced from 8192 for faster updates (~34 min vs 136 min)
    offset_ratio: 1.0
    min_roc_score: 0.5
    min_activity_score: 0.5
    min_direction_score: 0.5
    direction_filter: "both"

# Dashboard enabled with 3-component display
dashboard:
  enabled: true

# Wandb enabled
wandb:
  enabled: true
  tags: ["sniper", "3_component", "progressive"]