curriculum:
  stage_1_beginner:
    max_cycles: 1
  stage_2_intermediate:
    enabled: false
  stage_3_advanced:
    enabled: false
  stage_4_specialization:
    enabled: false
dashboard:
  enabled: false
env:
  max_episode_steps: 256
  reward:
    pnl_coefficient: 91.91980149213153
experiment_name: fx_ai_foundation_trial_106
logging:
  console_enabled: true
  file_enabled: false
  level: INFO
  log_actions: false
  log_features: false
mode: train
model:
  d_model: 128
  dropout: 0.08574222492594363
  n_layers: 7
training:
  batch_size: 128
  checkpoint_interval: 2
  continue_training: false
  entropy_coef: 0.022576460318493138
  eval_episodes: 3
  eval_frequency: 2
  gamma: 0.9735264422318117
  learning_rate: 0.0008120966505613017
  n_epochs: 4
  rollout_steps: 2048
  total_updates: 5
wandb:
  enabled: false
  notes: 'Phase 1: Foundation hyperparameter optimization'
  project: fx-ai-optuna-foundation
  save_model: false
  tags:
  - optuna
  - phase1
  - foundation
  - optuna
  - trial_106
