curriculum:
  stage_1_beginner:
    max_cycles: 2
    max_updates: 10
  stage_2_intermediate:
    enabled: false
  stage_3_advanced:
    enabled: false
  stage_4_specialization:
    enabled: false
dashboard:
  enabled: false
env:
  max_episode_steps: 512
  reward:
    pnl_coefficient: 102.24356499582109
experiment_name: fx_ai_foundation_trial_216
logging:
  console_enabled: true
  file_enabled: false
  level: INFO
  log_actions: false
  log_features: false
mode: train
model:
  d_model: 128
  dropout: 0.056789854486787326
  n_layers: 4
training:
  batch_size: 64
  checkpoint_interval: 5
  continue_training: false
  entropy_coef: 0.02014317299828409
  eval_episodes: 5
  eval_frequency: 5
  gamma: 0.9891400711712014
  learning_rate: 0.00022077713059951988
  n_epochs: 4
  rollout_steps: 2048
  total_updates: 10
wandb:
  enabled: false
  notes: 'Phase 1: Foundation hyperparameter optimization'
  project: fx-ai-optuna-foundation
  save_model: false
  tags:
  - optuna
  - phase1
  - foundation
  - optuna
  - trial_216
