curriculum:
  stage_1_beginner:
    max_cycles: 1
  stage_2_intermediate:
    enabled: false
  stage_3_advanced:
    enabled: false
  stage_4_specialization:
    enabled: false
dashboard:
  enabled: false
env:
  max_episode_steps: 256
  reward:
    pnl_coefficient: 125.93488414232718
experiment_name: fx_ai_foundation_trial_109
logging:
  console_enabled: true
  file_enabled: false
  level: INFO
  log_actions: false
  log_features: false
mode: train
model:
  d_model: 128
  dropout: 0.06537632355355812
  n_layers: 4
training:
  batch_size: 64
  checkpoint_interval: 2
  continue_training: false
  entropy_coef: 0.03678838294409871
  eval_episodes: 3
  eval_frequency: 2
  gamma: 0.9938689549303106
  learning_rate: 0.00015263707169053988
  n_epochs: 4
  rollout_steps: 2048
  total_updates: 5
wandb:
  enabled: false
  notes: 'Phase 1: Foundation hyperparameter optimization'
  project: fx-ai-optuna-foundation
  save_model: false
  tags:
  - optuna
  - phase1
  - foundation
  - optuna
  - trial_109
