# Optuna Override - Pure Hyperparameter Optimization
# Completely bypasses continuous training features for clean trials
training:
  continue_training: false  # Always start fresh
  rollout_steps: 2048      # Reasonable for learning
  n_epochs: 3              # Sufficient for comparison
  checkpoint_interval: 999999  # Effectively disable
  eval_frequency: 999999   # Disable evaluations
  seed: 42                 # Fixed seed for reproducibility

env:
  max_steps: 2048  # Match rollout_steps
  training_manager:
    mode: "optuna"  # New mode for complete bypass
    
    # Disable ALL termination logic
    termination:
      training_max_episodes: 100     # Fixed episode count
      training_max_updates: 20       # Fixed update count
      training_max_cycles: 1         # Single cycle only
      intelligent_termination: false # No smart termination
      plateau_patience: 999999       # Never detect plateau
      degradation_threshold: 999.0   # Never detect degradation
    
    # Completely disable continuous training
    continuous:
      enabled: false               # Master switch (NEW)
      bypass_all_features: true    # Complete bypass (NEW)
      performance_window: 999999   # Effectively disabled
      recommendation_frequency: 999999  # Never recommend
      checkpoint_frequency: 999999 # Never checkpoint
      
      evaluation:
        frequency: 999999        # Never evaluate
        episodes: 0              # No evaluation episodes
      
      adaptation_enabled: false  # No data adaptation
      advisory_enabled: false    # No advisory (NEW)
      model_versioning: false    # No versioning (NEW)
      best_model_tracking: false # No tracking (NEW)
    
    # Fixed data selection
    data_lifecycle:
      enabled: true
      
      cycles:
        day_max_episodes: null
        day_max_updates: null
        day_max_cycles: 1
      
      # Fixed data for all trials
      adaptive_data:
        symbols: ["MLGO"]
        date_range: ["2025-02-20", "2025-02-28"]
        day_score_range: [0.5, 1.0]
        roc_range: [-1.0, 1.0]
        activity_range: [0.5, 1.0]
        
        # Deterministic selection
        day_selection_mode: "sequential"
        reset_point_selection_mode: "sequential"
        randomize_order: false  # No randomization (NEW)
      
      preloading:
        preload_enabled: false

# Disable all external integrations
wandb:
  enabled: false

dashboard:
  enabled: false  # Avoid port conflicts

captum:
  enabled: false

# Clean metrics output
metrics:
  optuna_mode: true  # Simple metric output (NEW)
  track_only_mean_reward: true  # Single metric (NEW)