curriculum:
  stage_1_beginner:
    max_cycles: 5
    max_updates: 5
  stage_2_intermediate:
    enabled: false
  stage_3_advanced:
    enabled: false
  stage_4_specialization:
    enabled: false
dashboard:
  enabled: false
env:
  max_episode_steps: 512
  reward:
    pnl_coefficient: 166.0607716353429
experiment_name: fx_ai_foundation_trial_226
logging:
  console_enabled: true
  file_enabled: false
  level: INFO
  log_actions: false
  log_features: false
mode: train
model:
  d_model: 64
  dropout: 0.07855452767845453
  n_layers: 5
training:
  batch_size: 64
  checkpoint_interval: 5
  continue_training: false
  entropy_coef: 0.005707825835535783
  eval_episodes: 5
  eval_frequency: 2
  gamma: 0.9870438641730465
  learning_rate: 0.00021990609618509834
  n_epochs: 4
  rollout_steps: 4096
wandb:
  enabled: false
  notes: 'Phase 1: Foundation hyperparameter optimization'
  project: fx-ai-optuna-foundation
  save_model: false
  tags:
  - optuna
  - phase1
  - foundation
  - optuna
  - trial_226
