# Production configuration overrides
model:
  d_model: 1024
  n_heads: 16
  n_layers: 6
  dropout: 0.2

training:
  learning_rate: 0.0001
  batch_size: 128
  rollout_steps: 8192
  total_updates: 1000

env:
  reward_v2:
    scale_factor: 100.0
    invalid_action_penalty:
      coefficient: 0.1

wandb:
  tags: ["production", "v2"]