# Quick Test Configuration - Minimal setup for fast iteration
# Use for rapid development and debugging

experiment_name: "quick_test"

# Environment - minimal settings
env:
  symbol: "MLGO"
  initial_capital: 25000.0
  max_episode_steps: 100  # Very short episodes

# Training - minimal iterations
training:
  total_updates: 10
  learning_rate: 3e-4
  rollout_steps: 512
  batch_size: 16
  n_epochs: 3

# Data - single day for speed
data:
  symbols: ["MLGO"]
  start_date: "2025-03-27"
  end_date: "2025-03-27"
  min_activity_score: 0.0
  training_order: "random"

# Simulation - simplified
simulation:
  allow_shorting: false
  execution_delay_ms: 0

# Activity scoring - minimal points
activity_scoring:
  reset_points_per_day: 3
  min_activity_threshold: 0.0

# Disable dashboard and W&B for speed
dashboard:
  enabled: false

wandb:
  enabled: false