# Quick Override - Fast Development Training
# Optimized for rapid development cycles and testing
training:
  rollout_steps: 256
  n_epochs: 3

env:
  # Quick episode length for development
  max_steps: 256
  
  training_manager:
    mode: "production"
    
    # Quick termination for development (for entire training)
    termination:
      training_max_episodes: null         # Quick episode limit for testing
      training_max_updates: null           # Quick update limit
      training_max_cycles: 3             # Quick cycle limit for development
      intelligent_termination: false  # Disabled for quick tests
      plateau_patience: 20      # Quick plateau detection
      degradation_threshold: 0.1  # More sensitive for quick feedback
    
    # Frequent continuous training for quick feedback
    continuous:
      performance_window: 10    # Small window for quick trends
      recommendation_frequency: 5  # Frequent recommendations
      checkpoint_frequency: 10  # Frequent checkpoints for safety
      
      # Centralized evaluation settings
      evaluation:
        frequency: 2          # Frequent evaluations for feedback
        episodes: 5           # Few episodes for speed
      
      # Quick adaptation
      adaptation_enabled: false
    
    # Simple adaptive data for development
    data_lifecycle:
      enabled: true
      
      # Data cycle management (when to switch days/reset points)
      cycles:
        day_max_episodes: null               # 5 episodes per day for quick testing
        day_max_updates: null            # No update limit per day
        day_max_cycles: 2                # Quick cycling for development
      
      # Random adaptive data selection for variety in development
      adaptive_data:
        symbols: ["MLGO"]
        date_range: ["2025-02-21", "2025-02-24"]  # [start_date, end_date] inclusive
        day_score_range: [0.0, 1.0]
        roc_range: [0.0, 1.0]    # Wider range for more data
        activity_range: [0.0, 1.0]
        
        # DAY SELECTION: Random for development variety  
        day_selection_mode: "sequential"           # Options: "sequential" (chronological), "quality_weighted" (by score), "random"
        
        # RESET POINT SELECTION: Random for development variety
        reset_point_selection_mode: "sequential"  # Options: "sequential" (by quality), "random"
      
      preloading:
        preload_enabled: false  # Disabled for simplicity

# Model configuration for quick development
model: {}

# Development W&B settings
wandb:
  enabled: true
  project: fx-ai-development
  tags: [development, quick]
  notes: "Quick development training"

# Captum feature attribution for development/debugging
captum:
  # Enable Captum analysis
  enabled: true
  
  # Fast methods for frequent analysis
  methods:
    - saliency  # Fastest method for development
  
  # Quick analysis parameters
  n_steps: 10  # Fast computation
  n_samples: 3  # Minimal samples
  
  # Development analysis settings
  analyze_branches: true
  analyze_fusion: false  # Skip for speed
  analyze_actions: true
  baseline_type: zero
  
  # Visualization for debugging
  save_visualizations: true
  visualization_dir: outputs/captum_dev
  heatmap_threshold: 0.05
  
  # Performance settings for development
  batch_analysis: false
  aggregate_features: true
  
  # Real feature groups based on actual FxAIv2 feature implementation
  feature_groups:
    # High-frequency features (1-second bars)
    hf_price_action:
      - price_velocity
      - price_acceleration
    hf_tape_analysis:
      - tape_imbalance
      - tape_aggression_ratio
    hf_quote_dynamics:
      - spread_compression
      - quote_velocity
      - quote_imbalance
    hf_volume_flow:
      - volume_velocity
      - volume_acceleration
    
    # Medium-frequency features (1m/5m bars)
    mf_candle_patterns:
      - 1m_position_in_current_candle
      - 5m_position_in_current_candle
      - 1m_body_size_relative
      - 5m_body_size_relative
      - 1m_position_in_previous_candle
      - 5m_position_in_previous_candle
      - 1m_upper_wick_relative
      - 1m_lower_wick_relative
      - 5m_upper_wick_relative
      - 5m_lower_wick_relative
    mf_ema_system:
      - distance_to_ema9_1m
      - distance_to_ema20_1m
      - distance_to_ema9_5m
      - distance_to_ema20_5m
      - ema_interaction_pattern
      - ema_crossover_dynamics
      - ema_trend_alignment
    mf_swing_analysis:
      - swing_high_distance_1m
      - swing_low_distance_1m
      - swing_high_distance_5m
      - swing_low_distance_5m
    mf_velocity_acceleration:
      - price_velocity_1m
      - price_velocity_5m
      - volume_velocity_1m
      - volume_velocity_5m
      - price_acceleration_1m
      - price_acceleration_5m
      - volume_acceleration_1m
      - volume_acceleration_5m
    mf_vwap_analysis:
      - distance_to_vwap
      - vwap_slope
      - price_vwap_divergence
      - vwap_interaction_dynamics
      - vwap_breakout_quality
      - vwap_mean_reversion_tendency
    mf_volume_dynamics:
      - relative_volume
      - volume_surge
      - cumulative_volume_delta
      - volume_momentum
    mf_professional_indicators:
      - professional_ema_system
      - professional_vwap_analysis
      - professional_momentum_quality
      - professional_volatility_regime
    mf_sequence_patterns:
      - trend_acceleration
      - volume_pattern_evolution
      - momentum_quality
      - pattern_maturation
    mf_aggregated_signals:
      - mf_trend_consistency
      - mf_volume_price_divergence
      - mf_momentum_persistence
    mf_adaptive_features:
      - volatility_adjusted_momentum
      - regime_relative_volume
    
    # Low-frequency features (daily context)
    lf_range_position:
      - daily_range_position
      - prev_day_range_position
      - price_change_from_prev_close
    lf_support_resistance:
      - support_distance
      - resistance_distance
      - whole_dollar_proximity
      - half_dollar_proximity
      - adaptive_support_resistance
    lf_time_context:
      - market_session_type
      - time_of_day_sin
      - time_of_day_cos
    lf_market_structure:
      - halt_state
      - time_since_halt
      - distance_to_luld_up
      - distance_to_luld_down
      - luld_band_width
    lf_session_context:
      - session_progress
      - market_stress
      - session_volume_profile
    lf_hf_summaries:
      - hf_momentum_summary
      - hf_volume_dynamics
      - hf_microstructure_quality
    
    # Portfolio features (position and P&L tracking)
    portfolio_position:
      - position_size_normalized  # Feature 0: -1 to 1
      - unrealized_pnl_normalized  # Feature 1: -2 to 2
      - time_in_position  # Feature 2: 0 to 2
      - cash_ratio  # Feature 3: 0 to 2
    portfolio_pnl:
      - session_pnl_percentage  # Feature 4: -1 to 1
      - max_favorable_excursion  # Feature 5: -2 to 2 (MFE)
      - max_adverse_excursion  # Feature 6: -2 to 2 (MAE)
    portfolio_trade_quality:
      - profit_giveback_ratio  # Feature 7: -1 to 1
      - recovery_ratio  # Feature 8: -1 to 1
      - trade_quality_score  # Feature 9: -1 to 1
  
  # Frequent analysis for development debugging
  callback:
    analyze_every_n_episodes: null   # Every 2 episodes
    analyze_every_n_updates: 5    # Every update (aggressive)
    save_to_wandb: true
    save_to_dashboard: true
    output_dir: outputs/captum_dev