# Quick test configuration - minimal 3-component sniper training
experiment_name: "quick_test"

# Reduced model for faster testing
model:
  d_model: 64
  n_layers: 2
  n_heads: 4
  hf_layers: 1
  mf_layers: 1
  lf_layers: 1

# Quick training settings
training:
  rollout_steps: 1024
  total_updates: 10
  checkpoint_interval: 5
  batch_size: 64
  eval_frequency: 5
  eval_episodes: 2
  early_stop_patience: 15

# Shorter episodes for quick testing
env:
  max_episode_steps: 128
  max_steps: 128

# Limited data range
data:
  start_date: "2025-04-25"
  end_date: "2025-04-29"

# Sniper momentum scanning
momentum_scanning:
  min_daily_move: 0.10
  min_volume_multiplier: 2.0
  direction_filter: "both"

# 3-Component scoring
three_component_scoring:
  reset_points_per_day: 30
  near_zero_threshold: 0.05
  direction_weight: 0.3
  roc_weight: 0.4
  activity_weight: 0.3

# Quick curriculum
curriculum:
  stage_1_beginner:
    episode_range: [0, 50]
    episode_length: 128
    batch_size: 1024
    min_roc_score: 0.2
    min_activity_score: 0.2
    min_direction_score: 0.2

# Dashboard disabled for CI/testing
dashboard:
  enabled: false

# Wandb disabled for quick tests
wandb:
  enabled: false