# Sweep Override - Hyperparameter Optimization
# Optimized for fast, deterministic trials with minimal overhead

env:
  training_manager:
    mode: "sweep"
    
    # Fixed termination for consistent trials (for entire training)
    termination:
      training_max_episodes: 500         # Fixed episode limit
      training_max_updates: 100          # Fixed update limit for fast trials
      training_max_cycles: 10           # Fixed cycle limit for consistency
      intelligent_termination: false  # Disabled for deterministic behavior
      plateau_patience: 999999  # Effectively disabled
      degradation_threshold: 1.0  # Effectively disabled
    
    # Limited continuous training for sweep
    continuous:
      performance_window: 20    # Smaller window
      recommendation_frequency: 20  # Less frequent recommendations
      checkpoint_frequency: 50  # Less frequent checkpoints
      
      # Centralized evaluation settings
      evaluation:
        frequency: 100         # Less frequent evaluation
        episodes: 3            # Fewer episodes for speed
      
      # Only safe data difficulty adaptation
      adaptation_enabled: true  # Only data changes, no training params
    
    # Simplified adaptive data for sweep
    data_lifecycle:
      enabled: true
      
      # Data cycle management (when to switch days/reset points)
      cycles:
        episode_max_steps: 256           # Steps per episode
        day_max_episodes: null           # No episode limit per day
        day_max_updates: null            # No update limit per day
        day_max_cycles: 2                # Quick cycling for sweep trials
      
      # Deterministic adaptive data selection for consistent sweep trials
      adaptive_data:
        symbols: ["MLGO"]
        date_range: [null, null]
        day_score_range: [0.7, 1.0]
        roc_range: [0.05, 1.0]
        activity_range: [0.0, 1.0]
        
        # DAY SELECTION: Sequential for deterministic behavior
        day_selection_mode: "sequential"           # Options: "sequential" (chronological), "quality_weighted" (by score), "random"
        
        # RESET POINT SELECTION: Sequential for deterministic behavior
        reset_point_selection_mode: "sequential"  # Options: "sequential" (by quality), "random"
      
      preloading:
        preload_enabled: false  # Disabled for faster trials

# Model configuration for sweep
model: {}

# Disable W&B for faster trials (can be overridden in sweep configs)
wandb:
  enabled: false