# config/callbacks/default.yaml
# Synchronized with CallbacksConfig dataclass

save_freq: 5                 # Save model every N updates
log_freq: 10                 # Log every N steps
save_best_only: false        # If true, only save models that improve mean reward

# Early stopping callback
early_stopping:
  enabled: true
  patience: 10
  min_delta: 0.0