# @package _global_

# Phase 2: Reward system optimization
# Optimizes reward coefficients with fixed foundation parameters

name: phase2_reward_optimization
description: "Phase 2: Reward system optimization with fixed foundation parameters from Phase 1"
version: "1.0"

dashboard_port: 8052
log_level: INFO
results_dir: sweep_results
generate_plots: true

studies:
  - study_name: fx_ai_reward
    direction: maximize
    metric_name: mean_reward
    storage: sqlite:///optuna_studies.db
    load_if_exists: true
    
    # Base config to use as starting point
    base_config: config
    
    # Evaluation settings for optuna trials
    evaluation_interval: 10000  # Run evaluation every N updates
    evaluation_episodes: 10     # Episodes per evaluation
    report_interval: 1          # Report to optuna every evaluation
    use_best_value: false       # Report current value, not best
    
    sampler:
      type: CmaEsSampler      # Better for continuous reward coefficients
      n_startup_trials: 10
      seed: 42
      warn_independent_sampling: false
    
    pruner:
      type: MedianPruner
      n_startup_trials: 6
      n_warmup_steps: 20
      interval_steps: 4
      n_min_trials: 4
    
    # Reward system parameters to optimize
    parameters:
      - name: env.reward.pnl_coefficient
        type: float
        low: 80.0
        high: 400.0
      
      - name: env.reward.holding_penalty_coefficient
        type: float
        low: 0.5
        high: 8.0
      
      - name: env.reward.drawdown_penalty_coefficient
        type: float
        low: 2.0
        high: 25.0
      
      - name: env.reward.profit_closing_bonus_coefficient
        type: float
        low: 50.0
        high: 250.0
      
      - name: env.reward.clean_trade_coefficient
        type: float
        low: 10.0
        high: 80.0
      
      - name: env.reward.base_multiplier
        type: int
        low: 2000
        high: 8000
      
      - name: env.reward.bankruptcy_penalty_coefficient
        type: float
        low: 20.0
        high: 100.0
      
      - name: env.reward.profit_giveback_penalty_coefficient
        type: float
        low: 1.0
        high: 8.0
      
      - name: env.reward.max_drawdown_penalty_coefficient
        type: float
        low: 5.0
        high: 30.0
      
      - name: env.reward.activity_bonus_per_trade
        type: float
        low: 0.01
        high: 0.1
      
      - name: env.reward.hold_penalty_per_step
        type: float
        low: 0.005
        high: 0.05
      
      - name: env.reward.max_holding_time_steps
        type: int
        low: 60
        high: 300
    
    n_trials: 75
    timeout: null
    n_jobs: 1
    catch_exceptions: true
    
    # Trial-specific config overrides
    trial_overrides:
      experiment_name: optuna_reward
      
      training:
        n_epochs: 2
        continue_training: false
        save_checkpoints: false
        
        # NOTE: Foundation parameters should be set manually
        # based on best results from Phase 1
        # learning_rate: 0.0003    # Example from Phase 1
        # batch_size: 64           # Example from Phase 1
        # entropy_coef: 0.01       # Example from Phase 1
        # gamma: 0.99              # Example from Phase 1
      
      model:
        # NOTE: Architecture parameters should be set manually
        # based on best results from Phase 1
        # d_model: 128             # Example from Phase 1
        # n_layers: 6              # Example from Phase 1
        # dropout: 0.1             # Example from Phase 1
      
      # Disable heavy callbacks during optimization
      callbacks:
        optuna:
          enabled: true
        continuous:
          enabled: false
        ppo_metrics:
          enabled: true
        execution_metrics:
          enabled: false
        portfolio_metrics:
          enabled: false
        model_metrics:
          enabled: false
        session_metrics:
          enabled: false
        captum_attribution:
          enabled: false
          
      # Disable wandb during optimization
      wandb:
        enabled: false
        
      # Disable dashboard for speed
      dashboard:
        enabled: false