method: bayes
metric:
  name: mean_reward
  goal: maximize
parameters:
  training.learning_rate:
    min: 0.00005
    max: 0.0005
  training.batch_size:
    values: [32, 64, 128]
  training.n_epochs:
    values: [4, 8, 12]
  training.gamma:
    min: 0.95
    max: 0.999
  training.gae_lambda:
    min: 0.90
    max: 0.98
  training.clip_epsilon:
    min: 0.1
    max: 0.3
  training.entropy_coef:
    min: 0.001
    max: 0.05
  model.dropout:
    min: 0.05
    max: 0.2
  model.d_model:
    values: [64, 128, 256]
  model.n_layers:
    values: [4, 6, 8]
  env.reward.pnl_coefficient:
    min: 50.0
    max: 200.0
  env.reward.holding_penalty_coefficient:
    min: 1.0
    max: 5.0
  env.reward.drawdown_penalty_coefficient:
    min: 2.0
    max: 10.0