# Captum Feature Attribution - Default Configuration
# This configuration maps to the actual feature names used in FxAIv2

captum:
  enabled: true
  
  # Attribution methods to use
  methods:
    - integrated_gradients  # Most accurate but slower
    - deep_lift            # Good balance of speed and accuracy
    - saliency             # Fastest, good for quick analysis
  
  # Method-specific parameters
  n_steps: 50           # Steps for integrated gradients
  n_samples: 25         # Samples for gradient SHAP
  
  # Analysis settings
  analyze_branches: true    # Analyze each transformer branch
  analyze_fusion: true      # Analyze attention fusion layer
  analyze_actions: true     # Analyze action head attributions
  baseline_type: zero       # Baseline type: zero, mean, random
  
  # Visualization settings
  save_visualizations: true
  visualization_dir: outputs/captum
  heatmap_threshold: 0.01
  
  # Performance settings
  batch_analysis: false
  max_batch_size: 32
  aggregate_features: true
  
  # Feature grouping definitions based on ACTUAL FxAIv2 features
  feature_groups:
    # High-Frequency Features (1-second bars) - 9 features total
    hf_price_action:
      - price_velocity          # 1-second price velocity
      - price_acceleration      # 1-second price acceleration
    
    hf_tape_analysis:
      - tape_imbalance         # Buy/sell tape imbalance
      - tape_aggression_ratio  # Aggressive vs passive orders
    
    hf_microstructure:
      - spread_compression     # Bid-ask spread compression
      - quote_velocity         # Quote update velocity
      - quote_imbalance        # Bid/ask size imbalance
    
    hf_volume_dynamics:
      - volume_velocity        # 1-second volume velocity
      - volume_acceleration    # 1-second volume acceleration
    
    # Medium-Frequency Features (1m/5m bars) - 43 features total
    mf_candle_patterns:
      - 1m_position_in_current_candle   # Position within current 1m candle
      - 5m_position_in_current_candle   # Position within current 5m candle
      - 1m_body_size_relative           # 1m candle body size
      - 5m_body_size_relative           # 5m candle body size
      - 1m_position_in_previous_candle  # Position in previous 1m candle
      - 5m_position_in_previous_candle  # Position in previous 5m candle
      - 1m_upper_wick_relative          # 1m upper wick size
      - 1m_lower_wick_relative          # 1m lower wick size
      - 5m_upper_wick_relative          # 5m upper wick size
      - 5m_lower_wick_relative          # 5m lower wick size
    
    mf_ema_system:
      - distance_to_ema9_1m             # Distance to 9 EMA on 1m
      - distance_to_ema20_1m            # Distance to 20 EMA on 1m
      - distance_to_ema9_5m             # Distance to 9 EMA on 5m
      - distance_to_ema20_5m            # Distance to 20 EMA on 5m
      - ema_interaction_pattern         # EMA crossover patterns
      - ema_crossover_dynamics          # EMA crossover momentum
      - ema_trend_alignment             # Multi-timeframe EMA alignment
    
    mf_swing_analysis:
      - swing_high_distance_1m          # Distance to 1m swing high
      - swing_low_distance_1m           # Distance to 1m swing low
      - swing_high_distance_5m          # Distance to 5m swing high
      - swing_low_distance_5m           # Distance to 5m swing low
    
    mf_velocity_acceleration:
      - price_velocity_1m               # 1-minute price velocity
      - price_velocity_5m               # 5-minute price velocity
      - volume_velocity_1m              # 1-minute volume velocity
      - volume_velocity_5m              # 5-minute volume velocity
      - price_acceleration_1m           # 1-minute price acceleration
      - price_acceleration_5m           # 5-minute price acceleration
      - volume_acceleration_1m          # 1-minute volume acceleration
      - volume_acceleration_5m          # 5-minute volume acceleration
    
    mf_vwap_analysis:
      - distance_to_vwap                # Distance to VWAP
      - vwap_slope                      # VWAP slope/momentum
      - price_vwap_divergence           # Price-VWAP divergence
      - vwap_interaction_dynamics       # VWAP touch/break dynamics
      - vwap_breakout_quality           # VWAP breakout strength
      - vwap_mean_reversion_tendency    # Mean reversion to VWAP
    
    mf_volume_dynamics:
      - relative_volume                 # Volume vs average
      - volume_surge                    # Volume spike detection
      - cumulative_volume_delta         # Cumulative buy/sell volume
      - volume_momentum                 # Volume trend strength
    
    mf_professional_indicators:
      - professional_ema_system         # Complex EMA analysis
      - professional_vwap_analysis      # Advanced VWAP metrics
      - professional_momentum_quality   # Momentum quality score
      - professional_volatility_regime  # Volatility classification
    
    mf_sequence_patterns:
      - trend_acceleration              # Multi-bar trend acceleration
      - volume_pattern_evolution        # Volume pattern development
      - momentum_quality                # Momentum consistency
      - pattern_maturation              # Pattern completion score
    
    mf_aggregated_signals:
      - mf_trend_consistency            # Cross-timeframe trend alignment
      - mf_volume_price_divergence      # Volume-price divergence
      - mf_momentum_persistence         # Momentum sustainability
    
    mf_adaptive_features:
      - volatility_adjusted_momentum    # Volatility-normalized momentum
      - regime_relative_volume          # Volume relative to regime
    
    # Low-Frequency Features (daily/session context) - 19 features total
    lf_range_position:
      - daily_range_position            # Position in daily range
      - prev_day_range_position         # Position vs yesterday's range
      - price_change_from_prev_close    # % change from prev close
    
    lf_support_resistance:
      - support_distance                # Distance to nearest support
      - resistance_distance             # Distance to nearest resistance
      - whole_dollar_proximity          # Distance to whole dollar
      - half_dollar_proximity           # Distance to half dollar
      - adaptive_support_resistance     # Dynamic S/R levels
    
    lf_time_context:
      - market_session_type             # Pre/regular/post market
      - time_of_day_sin                 # Time encoding (sin)
      - time_of_day_cos                 # Time encoding (cos)
      - session_progress                # Progress through session
    
    lf_market_structure:
      - halt_state                      # Trading halt status
      - time_since_halt                 # Time since last halt
      - distance_to_luld_up             # Distance to upper limit
      - distance_to_luld_down           # Distance to lower limit
      - luld_band_width                 # LULD band width
      - market_stress                   # Market stress indicator
      - session_volume_profile          # Intraday volume profile
    
    lf_hf_summary:
      - hf_momentum_summary             # HF momentum aggregation
      - hf_volume_dynamics              # HF volume summary
      - hf_microstructure_quality       # HF market quality
    
    # Portfolio Features - 10 features total
    portfolio_position:
      - position_size                   # Normalized position size (-1 to 1)
      - position_pnl                    # Unrealized P&L (normalized)
      - time_in_position                # Holding time (normalized)
      - cash_ratio                      # Available cash ratio
    
    portfolio_risk:
      - position_volatility             # Position-specific volatility
      - pnl_volatility                  # P&L volatility
    
    portfolio_trade_quality:
      - mfe_ratio                       # Max favorable excursion ratio
      - mae_ratio                       # Max adverse excursion ratio
      - recovery_ratio                  # Recovery from drawdown
      - trade_efficiency                # Current P&L vs MFE/MAE range
  
  # Callback settings
  callback:
    analyze_every_n_episodes: 10      # Run analysis every N episodes
    analyze_every_n_updates: 5        # Run analysis every N PPO updates
    save_to_wandb: true               # Log results to Weights & Biases
    save_to_dashboard: true           # Send results to live dashboard
    output_dir: outputs/captum        # Directory for analysis reports