# config/training/continuous.yaml
# Configuration for continuous training
# This can be included in the defaults section of config.yaml

# Inherits regular PPO settings but adds continuous training settings
defaults:
  - ppo

# Paths and settings specific to continuous training
enabled: true
load_best_model: true
best_models_dir: "${hydra:runtime.cwd}/best_models"
model_prefix: "${data.symbol}"
max_best_models: 5
version_tracking: true
startup_evaluation: false
checkpoint_sync_frequency: 2  # How often to sync checkpoints to best_models directory

# Set to higher value than regular PPO to enable longer continued training
total_updates: 2

# Learning rate decay for continued training
lr_annealing:
  enabled: true
  min_lr: 1e-5
  decay_factor: 0.7  # How much to reduce LR after each continuation