# Configuration for comprehensive SHAP feature attribution
# This shows how to configure the SHAP analyzer with different settings

defaults:
  - _self_
  - /config@_here_

# SHAP Attribution Configuration
attribution_update_frequency: 10  # Run SHAP every N updates (10 for detailed, 50 for light)

# Model configuration with SHAP settings
model:
  # Enable/disable SHAP attribution
  enable_attribution: true
  
  # SHAP analyzer configuration
  shap_config:
    # Master switch - set to false to completely disable
    enabled: true
    
    # Analysis frequency
    update_frequency: ${attribution_update_frequency}
    
    # Performance settings
    max_samples_per_analysis: 5  # Limit samples for performance
    background_samples: 10  # Background data for baseline
    batch_size: 4  # Batch size for GPU processing
    
    # Attribution methods to use
    methods:
      - gradient_shap  # Fast and stable
      - integrated_gradients  # More accurate but slower
    primary_method: gradient_shap
    
    # Feature analysis settings
    top_k_features: 50  # Track top 50 features
    dead_feature_threshold: 0.001  # Threshold for dead features
    interaction_top_k: 20  # Top feature interactions
    
    # Advanced analysis
    analyze_interactions: true  # Feature interaction analysis
    analyze_gradients: true  # Gradient analysis
    track_attention: true  # Attention pattern tracking
    detect_outliers: true  # Outlier detection
    
    # Tracking settings
    history_length: 100  # History buffer size
    trend_window: 10  # Window for trend analysis
    
    # Visualization settings
    save_plots: true  # Save visualizations
    plot_dir: outputs/shap_plots
    plot_formats: [png]
    plot_dpi: 150  # Lower for faster saves
    
    # Integration settings
    log_to_wandb: true  # Log to Weights & Biases
    dashboard_update: true  # Update dashboard
    dashboard_update_freq: 5  # Update dashboard every N analyses
    
    # GPU settings
    use_gpu: true  # Use GPU if available
    
# Example configurations for different use cases:

# Light analysis (every 50 updates, minimal features)
shap_light:
  attribution_update_frequency: 50
  model:
    shap_config:
      max_samples_per_analysis: 3
      top_k_features: 20
      analyze_interactions: false
      save_plots: false
      plot_dpi: 100

# Heavy analysis (every 10 updates, all features)  
shap_heavy:
  attribution_update_frequency: 10
  model:
    shap_config:
      max_samples_per_analysis: 10
      top_k_features: 100
      analyze_interactions: true
      save_plots: true
      plot_dpi: 200
      methods:
        - gradient_shap
        - integrated_gradients
        - deep_lift

# Disabled (no SHAP analysis)
shap_disabled:
  model:
    enable_attribution: false
    shap_config:
      enabled: false