# conf/env/default.yaml
# Default environment configuration

# Basic environment parameters
random_reset: true
state_dim: 1000
max_steps: 500

# Reward parameters
reward_type: "momentum"  # Options: "momentum", "sharpe", "sortino", "custom"
reward_scaling: 1.0

# Trading parameters
trade_penalty: 0.1
hold_penalty: 0.0
max_position: 1.0  # Maximum position size (1.0 = 100% of available capital)