# config/env/trading.yaml
# Environment configuration for momentum trading

# General parameters
state_dim: 6000  # Increased from 1000 to 6000 to accommodate the actual state size
max_steps: 500
normalize_state: true
random_reset: true
max_position: 1.0
render_mode: "human"
position_multipliers: [ 0.25, 0.5, 0.75, 1.0 ]
max_episode_loss_percent: 0.5
bankruptcy_threshold_factor: 0.5
max_invalid_actions_per_episode: 20
training_mode: backtesting


# Reward configuration
reward:
  type: "momentum"
  scaling: 2.0
  trade_penalty: 0.1
  hold_penalty: 0.0
  early_exit_bonus: 0.5
  flush_prediction_bonus: 2.0

  # Strategy thresholds
  momentum_threshold: 0.5
  volume_surge_threshold: 5.0
  tape_speed_threshold: 3.0
  tape_imbalance_threshold: 0.7




