# config/env/trading.yaml
# Environment configuration for momentum trading - synchronized with EnvConfig

# General parameters
training_mode: "backtesting"
render_interval: 10
max_episode_loss_percent: 0.9
bankruptcy_threshold_factor: 0.9
max_invalid_actions_per_episode: 50000

state_dimension: 6000  # Increased to accommodate the actual state size
max_steps: 2048
normalize_state: true
random_reset: true
max_position: 1.0
position_multipliers: [0.25, 0.5, 0.75, 1.0]
render_mode: "dashboard" # "human", "rgb_array" or "dashboard"

dashboard:
  enabled: true
  update_frequency: 1 # Update frequency in seconds
  max_history_length: 1000 # Number of recent actions/fills to display

# Reward configuration
reward:
  weight_equity_change: 1.0
  weight_realized_pnl: 0.1
  penalty_transaction_fill: 0.005
  penalty_holding_inaction: 0.0001
  penalty_drawdown_step: 0.2
  penalty_invalid_action: 0.05
  terminal_penalty_bankruptcy: 20.0
  terminal_penalty_max_loss: 10.0
  reward_scaling_factor: 0.01
  log_reward_components: true


