# config/config.yaml
defaults:
  - base_config
  - model: transformer  # Main model configuration
  - env: trading  # Environment configuration
  - data: databento  # Data source configuration
  - training: ppo  # PPO algorithm parameters
  - wandb: default  # Weights & Biases integration
  - _self_

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.override_dirname}

# Quick test mode for debugging
quick_test: false

# Callbacks configuration
callbacks:
  save_freq: 5  # Save frequency in update iterations
  log_freq: 10  # TensorBoard logging frequency in steps
  early_stopping:
    enabled: true
    patience: 10
    min_delta: 0.0

# Simulation configuration
simulation:
  feature_config:
    hf_seq_len: 60
    hf_feat_dim: 20
    mf_seq_len: 30
    mf_feat_dim: 15
    lf_seq_len: 30
    lf_feat_dim: 10
    static_feat_dim: 15
    use_volume_profile: true
    use_tape_features: true
    use_level2_features: true
  market_config:
    slippage_factor: 0.001
  execution_config:
    commission_per_share: 0.0
  portfolio_config:
    initial_cash: 100000.0