# config/config.yaml

defaults:
  - _self_
  - model: transformer
  - env: momentum_trading
  - data: databento
  - training: ppo
  - wandb: default  # Include W&B configuration

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.override_dirname}

# Quick test mode for debugging
quick_test: false

# Callbacks configuration
callbacks:
  save_freq: 5  # Save frequency in update iterations
  log_freq: 10  # TensorBoard logging frequency in steps
  early_stopping:
    enabled: true
    patience: 10
    min_delta: 0.0