# config/config.yaml
defaults:
  - model: transformer            # Main model configuration
  - env: trading                  # Environment configuration
  - data: databento               # Data source configuration
  - training: continuous          # Continuous training with PPO
  - wandb: default                # Weights & Biases integration
  - simulation: default           # Simulation parameters
  - callbacks: default            # Callbacks configuration
  - _self_

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.override_dirname}

# Quick test mode for debugging
quick_test: false

# Project name
project_name: "Fx AI"

# Dashboard configuration
dashboard:
  enabled: true  # Enabled by default for better monitoring
  port: 8050
  open_browser: true
  update_interval: 500  # milliseconds
