# conf/quick_test.yaml
# Quick test configuration - overrides for faster development iterations
# Usage: python main.py +quick_test=true

defaults:
  - override /model: lightweight

# Override training parameters for quick testing
training:
  total_updates: 1
  n_episodes_per_update: 2
  batch_size: 32
  n_epochs: 3
  buffer_size: 1024

# Environment with shorter episodes
env:
  max_steps: 100

# Data with shorter period if needed
data:
  start_date: "2025-03-27"
  end_date: "2025-03-27"