# Training Default Configuration
# @package _global_

# Use structured config defaults
defaults:
  - model: transformer
  - model_storage: default
  - training: default
  - env: trading
  - data: databento
  - simulation: default
  - scanner: momentum
  - logging: default
  - callbacks: default
  - rewards: default
  - _self_

# Override specific training settings
training:
  device: "mps"
  learning_rate: 1.5e-4
  batch_size: 64
  
  training_manager:
    mode: "training"
    termination_max_episodes: 1000
    termination_max_updates: 500
    eval_frequency: 50
    eval_episodes: 10
    symbols: ["MLGO"]
    date_range: ["2025-05-21", "2025-05-21"]

# Logging configuration
logging:
  level: "INFO"
  console_enabled: true

# Evaluation configuration
evaluation:
  enabled: true
  seed: 42
  deterministic_actions: true
  use_fixed_episodes: true
  episodes: 10
  episode_selection: "diverse"