# Feature extraction configuration

# Feature dimensions
hf_seq_len: 60  # High-frequency sequence length (1s data)
hf_feat_dim: 20  # High-frequency feature dimension
mf_seq_len: 30  # Medium-frequency sequence length (1m data)
mf_feat_dim: 15  # Medium-frequency feature dimension
lf_seq_len: 30  # Low-frequency sequence length (5m data)
lf_feat_dim: 10  # Low-frequency feature dimension
static_feat_dim: 3  # Static feature dimension

# Feature normalization
feature_normalization: "standardize"
moving_avg_window: 20

# Feature groups
use_volume_profile: true
use_tape_features: true
use_level2_features: true
use_support_resistance: true
use_vwap: true
use_momentum: true

# Technical indicators
indicators:
  ema:
    - 9
    - 20
    - 200
  macd:
    fast: 12
    slow: 26
    signal: 9
  rsi:
    period: 14
  bollinger:
    period: 20
    std_dev: 2.0