name: comprehensive_hyperparameter_search
description: Comprehensive hyperparameter search for FxAI trading system
version: "1.0"

dashboard_port: 8052
log_level: INFO
results_dir: optuna_results
notify_on_complete: false
save_study_plots: true
max_concurrent_trials: 4
gpu_per_trial: 1.0

studies:
  - study_name: fx_ai_comprehensive
    direction: maximize
    metric_name: mean_reward
    storage: sqlite:///optuna_studies.db
    load_if_exists: true
    
    sampler:
      type: TPESampler
      n_startup_trials: 20
      n_ei_candidates: 24
      multivariate: true
      consider_prior: true
      prior_weight: 1.0
      consider_magic_clip: true
      seed: 42
    
    pruner:
      type: MedianPruner
      n_startup_trials: 10
      n_warmup_steps: 50
      interval_steps: 10
      n_min_trials: 5
    
    parameters:
      # Training hyperparameters
      - name: training.learning_rate
        type: float_log
        low: 0.00001
        high: 0.001
      
      - name: training.batch_size
        type: categorical
        choices: [32, 64, 128, 256]
      
      - name: training.n_epochs
        type: int
        low: 4
        high: 16
      
      - name: training.gamma
        type: float
        low: 0.95
        high: 0.999
      
      - name: training.gae_lambda
        type: float
        low: 0.9
        high: 0.99
      
      - name: training.clip_epsilon
        type: float
        low: 0.05
        high: 0.3
      
      - name: training.entropy_coef
        type: float_log
        low: 0.0001
        high: 0.1
      
      - name: training.value_coef
        type: float
        low: 0.1
        high: 1.0
      
      - name: training.max_grad_norm
        type: float
        low: 0.1
        high: 1.0
      
      # Model architecture
      - name: model.d_model
        type: categorical
        choices: [64, 128, 256]
      
      - name: model.n_layers
        type: int
        low: 3
        high: 10
      
      - name: model.n_heads
        type: categorical
        choices: [4, 8, 16]
      
      - name: model.dropout
        type: float
        low: 0.0
        high: 0.3
      
      - name: model.d_ff
        type: categorical
        choices: [512, 1024, 2048, 4096]
      
      # Reward system coefficients
      - name: env.reward.pnl_coefficient
        type: float
        low: 50.0
        high: 500.0
      
      - name: env.reward.holding_penalty_coefficient
        type: float
        low: 0.5
        high: 10.0
      
      - name: env.reward.drawdown_penalty_coefficient
        type: float
        low: 1.0
        high: 30.0
      
      - name: env.reward.profit_closing_bonus_coefficient
        type: float
        low: 20.0
        high: 200.0
      
      - name: env.reward.clean_trade_coefficient
        type: float
        low: 5.0
        high: 100.0
      
      - name: env.reward.bankruptcy_penalty_coefficient
        type: float
        low: 10.0
        high: 100.0
      
      - name: env.reward.max_drawdown_penalty_coefficient
        type: float
        low: 5.0
        high: 50.0
      
      # Environment settings
      - name: env.max_episode_steps
        type: categorical
        choices: [256, 512, 768, 1024]
      
      - name: env.early_stop_loss_threshold
        type: float
        low: 0.8
        high: 0.95
    
    n_trials: 200
    timeout: 86400  # 24 hours
    n_jobs: 1
    catch_exceptions: true
    
    training_config:
      mode: train
      experiment_name: optuna_comprehensive
      config: momentum_training
      
      training:
        total_updates: 200
        checkpoint_interval: 50
        eval_frequency: 25
        eval_episodes: 10
        rollout_steps: 2048
        continue_training: false
        use_lr_annealing: true
        lr_annealing_factor: 0.7
        lr_annealing_patience: 50
      
      env:
        symbol: MLGO
        initial_capital: 25000
        training_mode: true
      
      data:
        provider: databento
        symbols: [MLGO]
        cache_enabled: true
      
      wandb:
        enabled: true
        project: fx-ai-optuna
        tags: [optuna, hyperparameter_search]
      
      dashboard:
        enabled: false
    
    episodes_per_trial: 4000
    eval_frequency: 100
    eval_episodes: 10
    early_stop_patience: 10
    early_stop_min_delta: 0.01
    save_checkpoints: true
    checkpoint_dir: optuna_checkpoints
    keep_best_n: 5