name: parallel_hyperparameter_search
description: Parallel search optimized for multi-GPU execution
version: "1.0"

dashboard_port: 8052
log_level: INFO
results_dir: optuna_results
save_study_plots: true
max_concurrent_trials: 8
gpu_per_trial: 0.5

studies:
  - study_name: fx_ai_parallel
    direction: maximize
    metric_name: mean_reward
    storage: sqlite:///optuna_studies.db
    load_if_exists: true
    
    sampler:
      type: TPESampler
      n_startup_trials: 20
      multivariate: true
      warn_independent_sampling: false
      seed: 42
    
    pruner:
      type: HyperbandPruner
      min_resource: 10
      max_resource: 100
      reduction_factor: 3
      n_min_trials: 5
    
    parameters:
      # Balanced parameter set for parallel search
      - name: training.learning_rate
        type: float_log
        low: 0.00002
        high: 0.0008
      
      - name: training.batch_size
        type: categorical
        choices: [32, 64, 128]
      
      - name: training.n_epochs
        type: int
        low: 4
        high: 12
      
      - name: training.gamma
        type: float
        low: 0.96
        high: 0.998
      
      - name: training.gae_lambda
        type: float
        low: 0.92
        high: 0.98
      
      - name: training.clip_epsilon
        type: float
        low: 0.1
        high: 0.25
      
      - name: training.entropy_coef
        type: float_log
        low: 0.0005
        high: 0.05
      
      - name: model.d_model
        type: categorical
        choices: [64, 128, 256]
      
      - name: model.n_layers
        type: int
        low: 4
        high: 8
      
      - name: model.dropout
        type: float
        low: 0.05
        high: 0.25
      
      - name: env.reward.pnl_coefficient
        type: float
        low: 80.0
        high: 400.0
      
      - name: env.reward.holding_penalty_coefficient
        type: float
        low: 0.8
        high: 6.0
      
      - name: env.reward.drawdown_penalty_coefficient
        type: float
        low: 2.0
        high: 20.0
      
      - name: env.reward.profit_closing_bonus_coefficient
        type: float
        low: 40.0
        high: 160.0
    
    n_trials: 200
    n_jobs: 8  # Run 8 trials in parallel
    catch_exceptions: true
    
    training_config:
      mode: train
      experiment_name: optuna_parallel
      config: momentum_training
      
      training:
        total_updates: 100  # Shorter for more trials
        checkpoint_interval: 25
        eval_frequency: 20
        eval_episodes: 5
        rollout_steps: 2048
        device: cuda
      
      env:
        symbol: MLGO
        max_episode_steps: 256
      
      wandb:
        enabled: true
        project: fx-ai-optuna
        tags: [optuna, parallel_search]
      
      dashboard:
        enabled: false
    
    episodes_per_trial: 2000
    eval_frequency: 50
    eval_episodes: 5
    save_checkpoints: true
    checkpoint_dir: optuna_parallel_checkpoints