name: quick_hyperparameter_search
description: Quick hyperparameter search focusing on key parameters
version: "1.0"

dashboard_port: 8052
log_level: INFO
results_dir: optuna_results
save_study_plots: true

studies:
  - study_name: fx_ai_quick
    direction: maximize
    metric_name: mean_reward
    storage: sqlite:///optuna_studies.db
    load_if_exists: true
    
    sampler:
      type: TPESampler
      n_startup_trials: 10
      multivariate: true
      seed: 42
    
    pruner:
      type: SuccessiveHalvingPruner
      min_resource: 10
      reduction_factor: 3
      n_min_trials: 3
    
    parameters:
      # Key training parameters only
      - name: training.learning_rate
        type: float_log
        low: 0.00005
        high: 0.0005
      
      - name: training.batch_size
        type: categorical
        choices: [64, 128]
      
      - name: training.n_epochs
        type: categorical
        choices: [6, 8, 10]
      
      - name: training.gamma
        type: float
        low: 0.97
        high: 0.995
      
      - name: training.entropy_coef
        type: float_log
        low: 0.001
        high: 0.05
      
      # Key model parameters
      - name: model.d_model
        type: categorical
        choices: [128, 256]
      
      - name: model.n_layers
        type: categorical
        choices: [6, 8]
      
      # Key reward parameters
      - name: env.reward.pnl_coefficient
        type: float
        low: 100.0
        high: 300.0
      
      - name: env.reward.holding_penalty_coefficient
        type: float
        low: 1.0
        high: 5.0
      
      - name: env.reward.profit_closing_bonus_coefficient
        type: float
        low: 50.0
        high: 150.0
    
    n_trials: 50
    n_jobs: 1
    catch_exceptions: true
    
    training_config:
      mode: train
      experiment_name: optuna_quick
      config: momentum_training
      
      training:
        total_updates: 100
        checkpoint_interval: 25
        eval_frequency: 25
        eval_episodes: 5
        rollout_steps: 2048
      
      env:
        symbol: MLGO
        max_episode_steps: 256
      
      wandb:
        enabled: true
        project: fx-ai-optuna
        tags: [optuna, quick_search]
      
      dashboard:
        enabled: false
    
    episodes_per_trial: 2000
    eval_frequency: 50
    eval_episodes: 5
    save_checkpoints: true