# config/simulation/default.yaml
# Synchronized with SimulationConfig dataclass

market_config:
  slippage_factor: 0.001

execution_config:
  allow_shorting: false
  mean_latency_ms: 250.0
  latency_std_dev_ms: 10.0
  base_slippage_bps: 1.5
  size_impact_slippage_bps_per_unit: 0.03
  max_total_slippage_bps: 50.0
  commission_per_share: 0.0007
  fee_per_share: 0.003
  min_commission_per_order: 0.1
  max_commission_pct_of_value: null

portfolio_config:
  initial_cash: 100000.0
  max_position_value_ratio: 2.0
  max_position_holding_seconds: 300