# config/simulation/default.yaml - FIXED: Enhanced with configurable position sizing

# Synchronized with SimulationConfig dataclass

market_config:
  slippage_factor: 0.001

execution_config:
  allow_shorting: false
  mean_latency_ms: 250.0
  latency_std_dev_ms: 10.0
  base_slippage_bps: 1.5
  size_impact_slippage_bps_per_unit: 0.03
  max_total_slippage_bps: 50.0
  commission_per_share: 0.0007
  fee_per_share: 0.003
  min_commission_per_order: 0.1
  max_commission_pct_of_value: null

portfolio_config:
  initial_cash: 25000.0
  # FIXED: Configurable position sizing with fixed dollar amounts
  # Instead of using percentage of equity/cash, use fixed dollar amounts for consistency
  # Size multipliers (25%, 50%, 75%, 100%) will be applied to this base amount
  default_position_value: 10000.0  # Base position size in USD
  max_position_value_ratio: 2.0    # Maximum position as ratio of total equity (for risk management)
  max_position_holding_seconds: 300

# FIXED: Additional configuration comments for clarity
#
# Position Sizing Logic:
# - BUY actions will use: default_position_value * size_multiplier
# - Where size_multiplier is: 0.25 (25%), 0.50 (50%), 0.75 (75%), or 1.0 (100%)
# - Example: With default_position_value=10000 and SIZE_50 action:
#   - Target buy value = $10,000 * 0.50 = $5,000
#   - Quantity = $5,000 / current_ask_price
#
# - SELL actions (when holding):
#   - Will sell size_multiplier percentage of current position
#   - Example: SIZE_50 sells 50% of current holdings
#
# - SHORT actions (if enabled):
#   - Will use same logic as BUY but for shorting
#   - Target short value = default_position_value * size_multiplier
#
# Risk Management:
# - max_position_value_ratio limits position size relative to total equity
# - Example: With max_position_value_ratio=2.0, max position = 2x current equity